""" Locators for eBay web tests. """
SEARCH_FIELD = "css:#gh-ac"
SEARCH_BUTTON = "xpath://*[@id='gh-btn']"
ADVANCED_SEARCH_LINK = "xpath://*[@id='gh-as-a']"
PRODUCT_CONDITIONS_DROPDOWN = "xpath://span[text()='Состояние товара']/ancestor::button"
SHIPMENTS_DROPDOWN = "xpath://span[text()='Доставка']/ancestor::button"
DROPDOWN_OPTION = "xpath://a/span[text()='{text}']"
FILTER_RESULT = "xpath://ul[@class='carousel__list']//div[text()='{text}']"
SHOPPING_CATEGORY_BUTTON = "xpath://li/a[text()='{text}']"
